README: delocalise the AMO URL, other suggestions
SeidSmatti/redditUntranslate pull request #2
Opened 2024-12-15 17:17 UTC by grahamperrin

Non-localised https://addons.mozilla.org/addon/reddituntranslate/ is better for an extension such as this.

Whilst here: a few other suggestions.

2024-12-15 17:19 UTC, grahamperrin commented
Please note, I have not needed to use the extension (yet). 

I assume that _direction_ might be truer than _redirection_. In other words, I assume that a URL is de-localised **before** an unwanted visit to its localised equivalent.

2024-12-15 17:23 UTC, grahamperrin commented
Side note: the localised `fr/firefox/` part of the link in <https://old.reddit.com/r/bugs/comments/1dfnsub/how_do_i_stop_the_automatic_translation_of_all/lkjbn2h/?context=3> …

2024-12-16 04:02 UTC, SeidSmatti commented
Thanks a lot for your contribution, I aggree with everything except the redirection part, the extension detects the localised url and redirects the user to the localised one, but it's a matter of interpretation here

> Please note, I have not needed to use the extension (yet).
> 
> I assume that _direction_ might be truer than _redirection_. In other words, I assume that a URL is de-localised **before** an unwanted visit to its localised equivalent.

2024-12-16 04:24 UTC, SeidSmatti requested changes
I would still put redirection here, but thanks a lot for all the rest

2024-12-16 04:42 UTC, grahamperrin commented on README.md
> +**redditUntranslate** removes language parameters that are automatically added to Reddit URLs, ensuring direction to original, non-translated content. This extension is particularly useful for users
```suggestion
**redditUntranslate** removes language parameters that are automatically added to Reddit URLs, ensuring redirection to original, non-translated content. This extension is particularly useful for users who prefer browsing Reddit in their default language without automatic translation.
```

2024-12-16 04:42 UTC, grahamperrin commented on README.md
> +Once installed, redditUntranslate works automatically. Simply browse to any Reddit URL, the extension will remove any language parameters, directing you to the original version of the site.
```suggestion
Once installed, redditUntranslate works automatically. Simply browse to any Reddit URL, the extension will remove any language parameters, redirecting you to the original version of the site.
```

2024-12-16 04:57 UTC, merged

2024-12-16 05:23 UTC, grahamperrin commented
Thank you!